In [12]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt




print(tf.__version__)
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))


2.18.0
Num GPUs Available:  0


## 1 - Create a tensor

In [2]:
scalar = tf.constant(7)
print(scalar)

tf.Tensor(7, shape=(), dtype=int32)


In [3]:
scalar.ndim

0

In [4]:
scalar.dtype

tf.int32

In [5]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
vector.dtype

tf.int32

In [8]:
matrix = tf.constant([[10, 7],
                        [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [10]:
changeable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [11]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

## 2 - Creating Random tensors

In [13]:
gen = tf.random.Generator.from_seed(42)
random_1 = gen.normal(shape=(3, 2))
random_2 = gen.normal(shape=(3, 2))
random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.17522676,  0.71105534],
        [ 0.54882437,  0.14896014],
        [-0.54757965,  0.61634356]], dtype=float32)>)

## 3 - Shuffle the order of elements in a tensor

In [21]:
tf.random.set_seed(42)
tf.random.shuffle(random_1, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [23]:
one_tf = tf.ones(shape=(5,5))

print(type(one_tf))

<class 'tensorflow.python.framework.ops.EagerTensor'>


In [24]:
print(type(matrix))

<class 'tensorflow.python.framework.ops.EagerTensor'>


In [25]:
print(type(changeable_tensor))

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


In [27]:
tf.rank(one_tf).numpy()

np.int32(2)

In [28]:
tf.add(one_tf, 45)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[46., 46., 46., 46., 46.],
       [46., 46., 46., 46., 46.],
       [46., 46., 46., 46., 46.],
       [46., 46., 46., 46., 46.],
       [46., 46., 46., 46., 46.]], dtype=float32)>

In [29]:
tf.multiply(one_tf, 45)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[45., 45., 45., 45., 45.],
       [45., 45., 45., 45., 45.],
       [45., 45., 45., 45., 45.],
       [45., 45., 45., 45., 45.],
       [45., 45., 45., 45., 45.]], dtype=float32)>

In [31]:
tf.expand_dims(one_tf, axis = -1)

<tf.Tensor: shape=(5, 5, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]], dtype=float32)>

In [32]:
one_tf[:, tf.newaxis, :]

<tf.Tensor: shape=(5, 1, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.]]], dtype=float32)>

In [33]:
one_tf.dtype

tf.float32

In [34]:
one_tf = tf.cast(one_tf, dtype = tf.float16)
one_tf.dtype

tf.float16

In [36]:
one_tf

<tf.Tensor: shape=(5, 5), dtype=float16, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float16)>

In [35]:
tf.reduce_sum(one_tf, axis=0)

<tf.Tensor: shape=(5,), dtype=float16, numpy=array([5., 5., 5., 5., 5.], dtype=float16)>

In [37]:
A = tf.constant([1, 2, 3, 4, 5, 6], shape=(3, 2))
A

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [39]:
tf.reduce_sum(A, axis=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 3,  7, 11], dtype=int32)>

In [43]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=(50,)), shape=(1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [44]:
tf.squeeze(G)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [55]:
np.random.seed(42)
H = np.random.choice([0, 1, 2], size=(50,))  

In [56]:
H = tf.constant(H)
H

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([2, 0, 2, 2, 0, 0, 2, 1, 2, 2, 2, 2, 0, 2, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 2, 2, 2, 1, 2, 1, 1, 2, 1, 2, 2, 0, 2, 0, 2, 2, 0,
       0, 2, 1, 0, 1, 1])>

In [58]:
tf.one_hot(H, depth=3)

<tf.Tensor: shape=(50, 3), dtype=float32, numpy=
array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
      

In [59]:
X = np.random.normal(size=(100,))
Y = X * 2 + 1 + np.random.normal(size=(100,))
X = tf.constant(X, dtype=tf.float32)
Y = tf.constant(Y, dtype=tf.float32)
X, Y

(<tf.Tensor: shape=(100,), dtype=float32, numpy=
 array([-0.1402185 , -0.0331934 , -0.74907655, -0.778382  ,  0.9488429 ,
         1.5808506 , -0.36817095,  0.37556463, -1.1931583 , -0.4090519 ,
        -0.44674146,  1.5242417 ,  0.3229998 , -1.3934169 , -2.1783342 ,
        -1.0438964 ,  0.1726937 ,  0.32419878,  0.74585956, -1.8365833 ,
         0.5644642 ,  0.02550067,  0.47319326,  0.6591906 ,  2.3407464 ,
         1.0709852 ,  0.09641648,  0.4191021 , -0.9530278 , -1.0478706 ,
        -1.8756768 , -1.3667822 ,  0.6363051 , -0.9067207 ,  0.4760426 ,
         1.3036612 ,  0.21158701,  0.59704465, -0.8963352 , -0.11198782,
         1.4689413 , -1.1238984 ,  0.9500054 ,  1.7265165 ,  0.4578851 ,
        -1.6842874 ,  0.32684523, -0.08111896,  0.46779475,  0.73612237,
        -0.7797019 , -0.8438964 , -0.15053385, -0.9655577 ,  0.15048908,
        -0.11342125,  2.6335282 , -1.0250909 , -0.7820478 ,  0.42394307,
         0.8727051 ,  2.287226  ,  1.6229205 ,  0.8237331 ,  0.29305926,
  

In [63]:
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(1,)),
    tf.keras.layers.Dense(1,activation='relu' )
])

model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [76]:
tf.keras.backend.clear_session()

In [77]:
model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
              metrics=['mae'])
model.fit(X, Y, epochs=100)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 2.0465 - mae: 2.0465  
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.0465 - mae: 2.0465 
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.0465 - mae: 2.0465 
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.0465 - mae: 2.0465 
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.0465 - mae: 2.0465 
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.0465 - mae: 2.0465 
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.0465 - mae: 2.0465 
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.0465 - mae: 2.0465 
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.0465 - mae: 2.0465 
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.0465 - mae: 2.0465 
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.0465 - mae: 2.0465
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.0465 - mae: 2.0465
Epoch 13/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/st

In [78]:
model.predict(tf.constant([0.5, 1.0, 2.0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step


array([[0.],
       [0.],
       [0.]], dtype=float32)

In [79]:
model(tf.constant([0.5, 1.0, 2.0]))

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.]], dtype=float32)>